spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/order-service
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true